### ISSUE TITLE
Guide to building

### ISSUE THREAD

**Issue by RossElliman** [SnakeManPMC/arma-3-OSM_Places_CSV2HPP#1]
How do we compile this project?

**Comment by SnakeManPMC** [comment]
With Qt? https://www.qt.io/download

Yeah I know I know, should add compiled programs and DLLs with my sources especially for those tools that are actually used in arma3 terrain making tutorials. But yeah, will see about getting it done, one day :)

**Comment by RossElliman** [comment]
Sorry for not getting back to you, turns out my friend didn't install the framework -_-
